import React from "react";
import ReactDOM from "react-dom";

import "bootstrap/dist/css/bootstrap.css";
// import "./static/vendor/jqueryui/jquery-ui.min.js";
import "./static/vendor/perfect-scrollbar/perfect-scrollbar.css";
import "./static/vendor/lightbox2/css/lightbox.css";
import "./static/vendor/animsition/css/animsition.css";
import "./static/vendor/slick/slick-theme.css";
import "./static/vendor/slick/slick.css";
import "./static/vendor/select2/select2.css";
import "./static/vendor/animate/animate.css";
import "./static/vendor/jqueryui/jquery-ui.structure.css";
import "./static/vendor/jqueryui/jquery-ui.css";
import "./static/vendor/jqueryui/jquery-ui.theme.css";
import "./static/vendor/daterangepicker/daterangepicker.css";
import "./static/vendor/bootstrap/css/bootstrap-reboot.css";
import "./static/vendor/bootstrap/css/bootstrap-grid.css";
import "./static/vendor/bootstrap/css/bootstrap.css";
import "./static/vendor/css-hamburgers/hamburgers.css";
import "./static/css/util.css";
import "./static/css/main.css";
import "./static/admin/css/rtl.css";
import "./static/admin/css/widgets.css";
import "./static/admin/css/changelists.css";
import "./static/admin/css/base.css";
import "./static/admin/css/login.css";
import "./static/admin/css/dashboard.css";
import "./static/admin/css/fonts.css";
import "./static/admin/css/forms.css";
import "./static/fonts/ionicons-2.0.1/css/ionicons.css";
import "./static/fonts/font-awesome-4.7.0/css/font-awesome.css";
import "./static/fonts/themify/themify-icons.css";
import "./static/fonts/themify/ie7/ie7.css";
import "./static/fonts/themify/demo-files/demo.css";

// import "./static/js/slick-custom.js";
// import "./static/js/main.js";
// import "./static/js/map-custom.js";
// import "./static/vendor/lightbox2/js/lightbox.js";
// import "./static/vendor/countdowntime/countdowntime.js";
// import "./static/vendor/animsition/js/animsition.js";
// import "./static/vendor/slick/slick.js";
// import "./static/vendor/select2/select2.js";
// import "./static/vendor/parallax100/parallax100.js";
// import "./static/vendor/daterangepicker/moment.js";
// import "./static/vendor/bootstrap/js/bootstrap.js";
// import "./static/vendor/bootstrap/js/tooltip.js";
// import "./static/vendor/bootstrap/js/popper.js";
// import "./static/fonts/themify/ie7/ie7.js";

import App from "./App";
import registerServiceWorker from "./registerServiceWorker";

ReactDOM.render(<App />, document.getElementById("root"));
registerServiceWorker();
